name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./customer/pom.xml
          mvn clean package -f ./delivery/pom.xml
          mvn clean package -f ./business-owner/pom.xml
          mvn clean package -f ./delivery-manager/pom.xml

      - name: Docker Build and push for Customer
        uses: docker/build-push-action@v4
        with:
          context: ./customer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer:latest
            ghcr.io/${{ github.repository }}/customer:${{ github.ref_name }}
            
      - name: Docker Build and push for Delivery
        uses: docker/build-push-action@v4
        with:
          context: ./delivery
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery:latest
            ghcr.io/${{ github.repository }}/delivery:${{ github.ref_name }}
            
      - name: Docker Build and push for BusinessOwner
        uses: docker/build-push-action@v4
        with:
          context: ./business-owner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/business-owner:latest
            ghcr.io/${{ github.repository }}/business-owner:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryManager
        uses: docker/build-push-action@v4
        with:
          context: ./delivery-manager
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery-manager:latest
            ghcr.io/${{ github.repository }}/delivery-manager:${{ github.ref_name }}
            
